x=input("Informe algo: ")
print("Tipo primitivo é: {}".format(type(x)))
print("É um numero inteiro? ", x.isnumeric())
print("Tem apenas espaços: {} ".format(x.isspace()))
print("É alfabetico: {}".format(x.isalpha()))
print("É alphanumerico: ",x.isalnum())
print("Está em maiusculo: ", x.isupper())
print("Está em minusculo: ", x.islower())
print("É decimal: {}".format(x.isdecimal()))
print("É maiusculo e minusculo: ", x.istitle() )
